name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Set up dependencies
        shell: bash
        run: |
          if [ "$RUNNER_OS" = "Linux" ]; then
            sudo apt-get update
            sudo apt-get install -y build-essential cmake pkg-config \
              portaudio19-dev libaubio-dev libsdl2-dev nlohmann-json3-dev
          elif [ "$RUNNER_OS" = "macOS" ]; then
            brew update
            brew install portaudio aubio sdl2 nlohmann-json
          else
            choco install -y portaudio aubio sdl2 || echo "Install dependencies manually"
          fi
      - name: Configure
        run: cmake -S . -B build
      - name: Build
        run: cmake --build build --parallel
